resources:
- oauth.yaml
- project-leaders.yaml
- self-provisioners.yaml
secretGenerator:
- name: htpass-secret
  namespace: openshift-config
  files:
  - htpasswd=htpasswd
generatorOptions:
  disableNameSuffixHash: true
